config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers_devise/sessions',
    passwords:     'customers_devise/passwords',
    registrations: 'customers_devise/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 ##管理者側

  namespace :admins do
    resources :customers, only: [:index,:show,:edit,:update]
    get 'facilities/:facility_id/calendar' ,to: 'facilities#calendar', as: 'facilities_calendar'
    resources :facilities, except: [:destroy] do
      resource :facility_comments, only: [:create, :destroy]
      collection do
        get 'top'
      end
    end
    resources :categories, only: [:index,:create,:edit,:update]
    resources :events, only: [:index, :show, :edit, :update, :destroy]
    get 'facilities/:facility_id/sub_facilities' ,to: 'sub_facilities#index', as: 'sub_facility_facilities'
    resources :sub_facilities, except: [:destroy]
    get 'facilities/:facility_id/informations' ,to: 'informations#index', as: 'information_facilities'
    resources :informations
  end

  ##会員側
  root to: 'homes#top'
  resource :customer, only: [:show, :edit, :update, :destroy] do
    resources :favorites, only: [:index]
    member do
      get 'withdraw'
    end
  end
  get 'events/:facility_id/new' ,to: 'events#new', as: 'new_event'
  resources :events do
    collection do
        get 'thanks'
        get 'cancel'
        get  'confirm'
        post 'confirm'
    end
  end
  get 'facilities/:facility_id/calendar' ,to: 'facilities#calendar', as: 'facilities_calendar'
  resources :facilities, only: [:index,:show] do
    get 'search', on: :collection
    resource :favorites, only: [:create, :destroy]
    resource :facility_comments, only: [:create, :destroy]
  end
  get 'facilities/:facility_id/sub_facilities' ,to: 'sub_facilities#index', as: 'sub_facility_facilities'
  resources :sub_facilities, only: [:index,:show]
  get 'facilities/:facility_id/informations' ,to: 'informations#index', as: 'information_facilities'
  resources :informations, only: [:index,:show]
  get 'homes/about' => 'homes#about'

end

app/models/facility.rb
class Facility < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :customers,  through: :events
  has_many :sub_facilities, dependent: :destroy
  has_many :categories,  through: :sub_facilities
  has_many :favorites
  has_many :facility_comments
  has_many :informations
  attachment :facility_image
  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
  #バリデーション
  with_options presence: true do
    validates :facility_name, length: {minimum: 1}
    validates :date
    validates :facility_phone
    validates :address
    validates :lending_time
    validates :introduction, length: {minimum: 1, maximum: 50,}
  end
  validates :use_status, inclusion: {in: [true, false]}
end

app/controllers/admins/facilities_controller.rb
class Admins::FacilitiesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @facilities = Facility.all.order("created_at DESC").limit(4)
    @events= Event.where(title: "予約済").limit(4)
    @c_events= Event.where(title: "キャンセル済")
  end
  def new
    @facility = Facility.new
  end
  def index
    @facilities = Facility.all.page(params[:page]).reverse_order
  end
  def create
    @facility = Facility.new(facility_params)
    if @facility.save
      redirect_to admins_facilities_path
    else
      render 'new'
    end
  end
  def show
    @facility = Facility.find(params[:id])
    @events = @facility.events
    @facility_comments = @facility.facility_comments
  end
  def edit
    @facility = Facility.find(params[:id])
  end
  def update
    @facility = Facility.find(params[:id])
    if @facility.update(facility_params)
      redirect_to admins_facility_path(@facility.id)
    else
      render 'edit'
    end
  end
  def calendar
    @events = Event.where(facility_id: params[:facility_id])
    @facility = Event.where(facility_id: params[:facility_id])
end
  private
  def facility_params
    params.require(:facility).permit(:facility_name, :facility_image, :address, :date, :lending_time, :facility_phone, :introduction, :use_status)
  end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  def index
    @categories = Category.all
    #distinctで同じ施設をまとめる
  	 if params[:category_name]
     @facilities = Category.find_by(category_name: params[:category_name]).facilities.page(params[:page]).reverse_order.distinct
    else
     @facilities = Facility.page(params[:page]).reverse_order
     end
  end
  def search
    @q_facilities = @q.result.page(params[:page]).reverse_order
    @categories = Category.all
    render :index
  end
  def show
     @facility = Facility.find(params[:id])
     @facility_comment = FacilityComment.new
     @facility_comments = @facility.facility_comments.page(params[:page]).reverse_order
  end
  def calendar
      @events = Event.where(facility_id: params[:facility_id])
      @facility = Event.where(facility_id: params[:facility_id])
  end
end

app/helpers/admins/facilities_helper.rb
module Admins::FacilitiesHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/admins/facilities/calendar.html.erb
 <div class="container">
  <div class= "row">
    <div class= "col-xs-12">
      <h2>カレンダー</h2>
    </div>
  </div>
  <div class="row">
    <div class= "col-xs-2">
      <div class="sidebar">
      <%= link_to("./", class: 'list-content') do %>
        <div class="sidebar-title">基本情報</div>
      <% end %>
      <%= link_to(admins_sub_facility_facilities_path, class: 'list-content') do %>
        <div class="sidebar-title">コート一覧</div>
      <% end %>
      <%= link_to(admins_facilities_calendar_path, class: 'list-content') do %>
        <div class="sidebar-title">カレンダー</div>
      <% end %>
      <%= link_to(admins_information_facilities_path, class: 'list-content') do %>
        <div class="sidebar-title">お知らせ</div>
        <% end %>
        </div>
      </div>
      <div class="col-xs-10">
          <p class="note">※「予約済」の場合は<span class="under-bule">青色</span>、「キャンセル済」の場合は<span class="under-red">赤色</span>で表示されます。</p>
        <div id="calendar"></div>
      </div>
  </div>
</div>
<%= render 'facilities/calendar_list' %>

app/views/admins/facilities/edit.html.erb
<div class ="container">
  <div class= "row">
    <div class= "col-xs-12">
      <h2>編集画面</h2>
    </div>
  </div>
    <div class= "row">
    <%= form_for(@facility, url:admins_facility_path(@facility.id)) do |f| %>
      <div class= "col-xs-7">
      <h3>施設画像</h3>
      <div id="image_view"></div>
      <%= attachment_image_tag @facility,:facility_image,:fill,400,316,format:'jpeg',fallback: "no_image.jpg", id:"orgin_img" %>
              <%= f.attachment_field :facility_image, id: "image_btn" %>
      </div>
      <div class= "col-xs-5">
      <h3>施設紹介</h3>
        <table class= "table">
        <tbody>
          <tr>
            <td>施設名</td>
            <td><%= f.text_field :facility_name %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= f.text_area :address %></td>
          </tr>
          <tr>
            <td>解放日</td>
            <td><%= f.text_field :date%></td>
          </tr>
          <tr>
            <td>解放時間</td>
            <td><%= f.text_field :lending_time %></td>
          </tr>
          <tr>
            <td>TEL</td>
            <td><%= f.text_field :facility_phone %></td>
          </tr>
          <tr>
            <td>紹介文</td>
            <td><%= f.text_area :introduction %></td>
          </tr>
          <tr>
            <td>使用ステータス</td>
            <td><%= f.select :use_status,[["使用可",true],["使用不可",false]] %></td>
          </tr>
          </tbody>

        </table>
        <%= f.submit "変更する" ,class:"btn btn-primary next", style:"width:50%;"%>
      </div>
      <% end %>
    </div>
</div>
<script>
$(function() {
    $('#image_btn').on('change', function(e) {
        // 1枚だけ表示する
        var file = e.target.files[0];
        console.log(file);
        if ( !file ){
            $('#image_view').html("");
            $('#orgin_img').show();
            return;
        }
        // ファイルリーダー作成
        var fileReader = new FileReader();
        if (file.type == 'video/mp4') {
            var dom = $("<video>");
        }
        else{
            var dom = $("<img>");
        }
        dom.attr('style','width:400px;','height:316px;');
        fileReader.onload = function() {
            // Data URIを取得
            console.log(this.result);
            var dataUri = this.result;
            dom.attr('src', dataUri);
            // img要素に表示
            $('#image_view').html(dom);
        }
        // ファイルをData URIとして読み込む
        fileReader.readAsDataURL(file);
        $('#orgin_img').hide();
    });
});
</script>

app/views/admins/facilities/index.html.erb
<div class="container">
  <div class= "row">
  <div class="col-xs-12">
  <h2>施設一覧</h2>
  </div>
  </div>
  <div class= "row">
  <a id="fab" href="/admins/facilities/new">
  <i class="fas fa-plus"></i>
  </a>
      <table class="table">
          <tr class="border">
            <th>施設ID</th>
            <th>施設</th>
            <th>コート数</th>
            <th>ステータス</th>
          </tr>
      <tbody>
        <% @facilities.each do |facility| %>
        <tr class="admins_table">
          <%= link_to(admins_facility_path(facility.id), class: 'list-content') do %>
          <td><%= facility.id %></td>
          <td><%= link_to facility.facility_name,admins_facility_path(facility.id) %></td>
          <td><%= facility.sub_facilities.count %></td>
          <% if  facility.use_status == true %>
          <td><%= link_to '使用可', admins_facility_path(facility), class:'btn btn-success'%></td>
          <% else  facility.use_status == false %>
          <td><%= link_to '使用不可', admins_facility_path(facility), class:'btn btn-danger'%></td>
          <% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
        </table>
    </div>
    <%= paginate @facilities, class: "paginate" %>
</div>

app/views/admins/facilities/new.html.erb
<div class ="container">
  <div class= "row">
    <div class= "col-xs-12">
      <h2>新規登録画面</h2>
    </div>
  </div>
    <div class= "row">
    <%= form_for(@facility, url:admins_facilities_path) do |f| %>
      <div class= "col-xs-7">
      <h3>施設画像</h3>
      <div id="image_view"></div>
      <%= attachment_image_tag @facility,:facility_image,:fill,300,200,format:'jpeg', fallback: "no_image.jpg",id:"orgin_img" %>
              <%= f.attachment_field :facility_image, id: "image_btn" %>
      </div>
      <div class= "col-xs-5">
      <h3>施設紹介</h3>
        <table class= "table">
        <tbody>
          <tr>
            <td>施設名</td>
            <td><%= f.text_field :facility_name %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= f.text_area :address %></td>
          </tr>
          <tr>
            <td>解放日</td>
            <td><%= f.text_field :date%></td>
          </tr>
          <tr>
            <td>解放時間</td>
            <td><%= f.text_field :lending_time %></td>
          </tr>
          <tr>
            <td>TEL</td>
            <td><%= f.text_field :facility_phone %></td>
          </tr>
          <tr>
            <td>紹介文</td>
            <td><%= f.text_area :introduction %></td>
          </tr>
          <tr>
            <td>使用ステータス</td>
            <td><%= f.select :use_status,[["使用可", true ],["使用不可", false ]] %></td>
          </tr>
          </tbody>

        </table>
        <%= f.submit "新規登録" ,class:"btn btn-primary next"%>
      </div>
      <% end %>
    </div>
</div>
<script>
$(function() {
    $('#image_btn').on('change', function(e) {
        // 1枚だけ表示する
        var file = e.target.files[0];
        console.log(file);
        if ( !file ){
            $('#image_view').html("");
            $('#orgin_img').show();
            return;
        }
        // ファイルリーダー作成
        var fileReader = new FileReader();
        if (file.type == 'video/mp4') {
            var dom = $("<video>");
        }
        else{
            var dom = $("<img>");
        }
        dom.attr('style','width:400px;','height:316px;');
        fileReader.onload = function() {
            // Data URIを取得
            console.log(this.result);
            var dataUri = this.result;
            dom.attr('src', dataUri);
            // img要素に表示
            $('#image_view').html(dom);
        }
        // ファイルをData URIとして読み込む
        fileReader.readAsDataURL(file);
        $('#orgin_img').hide();
    });
});
</script>

app/views/admins/facilities/show.html.erb
<div class ="container">
  <div class= "row">
    <div class= "col-xs-12">
      <h2>詳細画面</h2>
    </div>
  </div>
    <div class="row">
      <div class= "col-xs-3">
        <div class="sidebar">
        <%= link_to(admins_facility_path(@facility.id), class: 'list-content') do %>
         <div class="sidebar-title">基本情報</div>
        <% end %>
        <%= link_to( admins_sub_facility_facilities_path(@facility.id), class: 'list-content') do %>
        <div class="sidebar-title">コート一覧</div>
        <% end %>
         <%= link_to(admins_facilities_calendar_path(@facility.id), class: 'list-content') do %>
        <div class="sidebar-title">カレンダー</div>
        <% end %>
        <%= link_to(admins_information_facilities_path(@facility.id), class: 'list-content') do %>
        <div class="sidebar-title">お知らせ</div>
        <% end %>
        </div>
        <%= link_to '編集する', edit_admins_facility_path, class: 'btn btn-primary', style:"width:100%;"%>
        </div>
        <div class= "col-xs-9">
        <h3>施設画像</h3>
        <div class="sub-img"><%= attachment_image_tag @facility,:facility_image,:fill,680,400,format:'jpeg',fallback: "no_image.jpg" %>
        <span id="favorite" class="glyphicon glyphicon-heart-empty"><%= @facility.favorites.count %></span></div>
        <h3>施設紹介</h3>
        <table class= "table">
        <tbody>
          <tr>
            <td>施設名</td>
            <td><%= @facility.facility_name %></td>
          </tr>

            <td>住所</td>
            <td><%= @facility.address %></td>
          </tr>
          <tr>
            <td>解放日</td>
            <td><%= @facility.date%></td>
          </tr>
          <tr>
            <td>解放時間</td>
            <td><%= @facility.lending_time %></td>
          </tr>
          <tr>
            <td>TEL</td>
            <td><%= @facility.facility_phone %></td>
          </tr>
          <tr>
            <td>紹介文</td>
            <td><%= @facility.introduction %></td>
          </tr>
          </tbody>
      </table>
      <!--コメント-->
      <h3>コメント一覧</h3>
      <div id="js-comment">
      <%= render 'facility_comments/comments', facility_comments: @facility_comments %>
      </div>
    </div>
  </div>
</div>

app/views/admins/facilities/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>トップページ</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6">
      <div class="top-box">
        <h3>最近登録した施設</h3>
        <table class="table">
          <tr class="border">
            <th>登録日</th>
            <th>施設名</th>
            <th></th>
          </tr>
          <tbody>
          <% @facilities.each do |facility| %>
            <tr>
              <td><%= facility.created_at.strftime("%Y年%m月%d日")%></td>
              <td><%= facility.facility_name%></td>
              <td><%= link_to "表示", admins_facility_path(facility.id), class:'btn btn-primary' %></td>
            </tr>
        <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="top-box">
        <h3>キャンセルされた施設</h3>
        <table class="table">
          <tr class="border">
            <th>キャンセル日</th>
            <th>施設名</th>
            <th>予約者名</th>
            <th></th>
          </tr>
          <tbody>
            <% @c_events.each do |event| %>
            <tr>
              <td><%= link_to event.updated_at.strftime("%Y年%m月%d日")%></td>
              <td><%= event.facility.facility_name %></td>
              <td><%= event.customer.last_name %><%= event.customer.first_name %></td>
              <td><%= link_to "表示", admins_event_path(event.id), class:'btn btn-primary' %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    </div>
    <div class="row">
    <div class="col-xs-6">
      <div class="top-box">
        <h3>最近予約された施設</h3>
        <table class="table">
          <tr class="border">
            <th>予約日</th>
            <th>施設名</th>
            <th>予約者名</th>
            <th></th>
          </tr>
          <tbody>
            <% @events.each do |event| %>
            <tr>
              <td><%= link_to event.created_at.strftime("%Y年%m月%d日") %></td>
              <td><%= event.facility.facility_name %></td>
              <td><%= event.customer.last_name %><%= event.customer.first_name %></td>
              <td><%= link_to "表示", admins_event_path(event.id), class:'btn btn-primary' %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    </div>
</div>