config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers_devise/sessions',
    passwords:     'customers_devise/passwords',
    registrations: 'customers_devise/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 ##管理者側

  namespace :admins do
    resources :customers, only: [:index,:show,:edit,:update]
    get 'facilities/:facility_id/calendar' ,to: 'facilities#calendar', as: 'facilities_calendar'
    resources :facilities, except: [:destroy] do
      resource :facility_comments, only: [:create, :destroy]
      collection do
        get 'top'
      end
    end
    resources :categories, only: [:index,:create,:edit,:update]
    resources :events, only: [:index, :show, :edit, :update, :destroy]
    get 'facilities/:facility_id/sub_facilities' ,to: 'sub_facilities#index', as: 'sub_facility_facilities'
    resources :sub_facilities, except: [:destroy]
    get 'facilities/:facility_id/informations' ,to: 'informations#index', as: 'information_facilities'
    resources :informations
  end

  ##会員側
  root to: 'homes#top'
  resource :customer, only: [:show, :edit, :update, :destroy] do
    resources :favorites, only: [:index]
    member do
      get 'withdraw'
    end
  end
  get 'events/:facility_id/new' ,to: 'events#new', as: 'new_event'
  resources :events do
    collection do
        get 'thanks'
        get 'cancel'
        get  'confirm'
        post 'confirm'
    end
  end
  get 'facilities/:facility_id/calendar' ,to: 'facilities#calendar', as: 'facilities_calendar'
  resources :facilities, only: [:index,:show] do
    get 'search', on: :collection
    resource :favorites, only: [:create, :destroy]
    resource :facility_comments, only: [:create, :destroy]
  end
  get 'facilities/:facility_id/sub_facilities' ,to: 'sub_facilities#index', as: 'sub_facility_facilities'
  resources :sub_facilities, only: [:index,:show]
  get 'facilities/:facility_id/informations' ,to: 'informations#index', as: 'information_facilities'
  resources :informations, only: [:index,:show]
  get 'homes/about' => 'homes#about'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_facilities, dependent: :destroy
  has_many :facilities, through: :sub_facilities
  #バリデーション追加
  validates :category_name, presence: true

  enum category_status: {"無効": false, "有効": true}
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
  before_action :authenticate_admin!
 def index
  @categories = Category.all
  @category = Category.new
 end
 def create
  category = Category.new(category_params)
    if category.save
      redirect_to admins_categories_path
    else
      @categories = Category.all
      render action: :index
    end
 end
 def edit
  @category = Category.find(params[:id])

 end
 def update
  category = Category.find(params[:id])
    if category.update(category_params)
      category = Category.find(params[:id])
      redirect_to admins_categories_path
    else
      render action: :edit
    end
 end
 private
  def category_params
    params.require(:category).permit(:category_name, :display)
  end
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/views/admins/categories/edit.html.erb
<div class="container">
 <h2>カテゴリ編集画面</h2>
 <%= form_for(@category,url: admins_category_path) do |f| %>
	<div class="form-inline">
	 <div class="form-group">
		 <label>カテゴリ<%= f.text_field :category_name %></label>
	 </div>
	 <div class="form-group">
		 <label>
		     <%= f.radio_button :display, 'true' %>有効
	     </label>
	     <label>
		 	 <%= f.radio_button :display, 'false' %>無効
	    </label>
	 </div>
	  <div class="form-group">
		 <label><%= f.submit '変更を保存する', class:"btn btn-primary" %></label>
     </div>
	</div>
 <% end %>
</div>

app/views/admins/categories/index.html.erb
<div class = "container">
  <div class= "row">
    <div class="col-xs-10 col-xs-offset-1">

        <h2>カテゴリ追加・一覧画面</h2>

        <!-- new category form -->
        <%= form_for :category,url: admins_categories_path do |f| %>
          <div class="form-inline">
          <div class="form-group">
            <label>カテゴリ<%= f.text_field :category_name %></label>
          </div>
          <div class="form-group">
            <label>
                <%= f.radio_button :display, 'true' %>有効
              </label>
              <label>
              <%= f.radio_button :display, 'false' %>無効
              </label>
          </div>
            <div class="form-group">
            <label><%= f.submit '追加', class:"btn btn-primary" %></label>
            </div>
          </div>
        <% end %>
        <!-- category index -->
        <table class="table category-index">
          <thead>
            <tr class="border">
              <th>カテゴリ</th>
              <th>状態</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
            <tr>
              <td><%= category.category_name %></td>
              <% if category.display == true %>
              <td>有効</td>
              <% else category.display == false %>
              <td>無効</td>
              <% end %>
              <td><%= link_to '編集', edit_admins_category_path(category.id), class:"btn btn-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

  </div>
</div>