config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers_devise/sessions',
    passwords:     'customers_devise/passwords',
    registrations: 'customers_devise/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 ##管理者側

  namespace :admins do
    resources :customers, only: [:index,:show,:edit,:update]
    get 'facilities/:facility_id/calendar' ,to: 'facilities#calendar', as: 'facilities_calendar'
    resources :facilities, except: [:destroy] do
      resource :facility_comments, only: [:create, :destroy]
      collection do
        get 'top'
      end
    end
    resources :categories, only: [:index,:create,:edit,:update]
    resources :events, only: [:index, :show, :edit, :update, :destroy]
    get 'facilities/:facility_id/sub_facilities' ,to: 'sub_facilities#index', as: 'sub_facility_facilities'
    resources :sub_facilities, except: [:destroy]
    get 'facilities/:facility_id/informations' ,to: 'informations#index', as: 'information_facilities'
    resources :informations
  end

  ##会員側
  root to: 'homes#top'
  resource :customer, only: [:show, :edit, :update, :destroy] do
    resources :favorites, only: [:index]
    member do
      get 'withdraw'
    end
  end
  get 'events/:facility_id/new' ,to: 'events#new', as: 'new_event'
  resources :events do
    collection do
        get 'thanks'
        get 'cancel'
        get  'confirm'
        post 'confirm'
    end
  end
  get 'facilities/:facility_id/calendar' ,to: 'facilities#calendar', as: 'facilities_calendar'
  resources :facilities, only: [:index,:show] do
    get 'search', on: :collection
    resource :favorites, only: [:create, :destroy]
    resource :facility_comments, only: [:create, :destroy]
  end
  get 'facilities/:facility_id/sub_facilities' ,to: 'sub_facilities#index', as: 'sub_facility_facilities'
  resources :sub_facilities, only: [:index,:show]
  get 'facilities/:facility_id/informations' ,to: 'informations#index', as: 'information_facilities'
  resources :informations, only: [:index,:show]
  get 'homes/about' => 'homes#about'

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_KATAKANA = /\A[\p{katakana}\p{blank}ー－]+\z/
    VALID_TELPHONE = /\A\d{10,11}\z/  # 電話番号
    with_options presence: true do
      validates :last_name
      validates :first_name
      validates :kana_last_name,  format: {
                                    with: VALID_KATAKANA,
                                    message: 'はカタカナで入力してください。'
                                  }
      validates :kana_first_name, format: {
                                    with: VALID_KATAKANA,
                                    message: 'はカタカナで入力してください。'
                                  }
      validates :telephone,             format: {
                                    with: VALID_TELPHONE,
                                    message: "の入力が間違っています（ハイフンなしの数字）"
                                  }
      validates :email,           format: {
                                    with: VALID_EMAIL_REGEX
                                  }
    end
  has_many :events, dependent: :destroy
  has_many :facilities,  through: :events
  has_many :favorites
  has_many :facility_comments

  # ユーザーのアカウントが有効であることを確認
  def active_for_authentication?
    super && member_status
  end
end

app/controllers/Customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end
  def show
    @customer = Customer.find(params[:id])
  end
  def edit
    @customer = Customer.find(params[:id])
  end
  def update
    customer = Customer.find(params[:id])
    if  customer.update(customer_params)
       redirect_to admins_customer_path
    else
   	   render action: :edit
    end
  end
    private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :telephone, :email, :member_status)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  def show
    @customer = current_customer
    @facility = Favorite.where(facility_id: params[:facility_id])
  end
  def edit
    @customer = current_customer
  end
  def update
    @customer = current_customer
    if  @customer.update(customer_params)
       redirect_to customer_path
    else
   	   render action: :edit
    end
  end
  def destroy
    @customer = current_customer
    if @customer.delete
       redirect_to root_path
    else
    	 render action: :destroy
    end
  end
  def withdraw

  end
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :telephone, :email)
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-5">
        <h3>登録情報編集画面</h3>
        <label>会員情報の編集</label><%= link_to "退会する", withdraw_customer_path, class:"btn btn-danger delete" %>
          <%= form_for(@customer) do |f| %>
            <table class="table">
              <tr>
               <td>氏名</td>
               <td><%= f.text_field:last_name %> <%= f.text_field:last_name %></td>
              </tr>
              <tr>
            	 <td>カナ</td>
               <td><%= f.text_field:kana_last_name %> <%= f.text_field:kana_last_name %></td>
              </tr>
              <tr>
            	 <td>電話番号</td>
               <td><%= f.text_field:telephone %></td>
              </tr>
              <tr>
            	 <td>メールアドレス</td>
               <td><%= f.text_field:email %></td>
              </tr>
            </table>
            <%= f.submit "編集内容を保存する", class:"btn btn-primary" %>
          <% end %>
      </div>
    </div>
</div>

app/views/customers/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>マイページ</h2>
        <h3>登録情報</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-6">
          <div class="profile">
            <h4 class="profile-title">個人設定</h4>
            <div class="profile-box">
              <i class="fas fa-user-cog"></i>
            </div>
            <div class="profile-box">
              <li class="profile-text"><%= link_to ">編集する", edit_customer_path %></li>
              <li class="profile-text"><%= link_to ">お気に入り施設", customer_favorites_path %></li>
              <li class="profile-text"><%= link_to ">退会手続きへ", edit_customer_path %></li>
            </div>
          </div>
          </div>
          <div class="col-xs-6">
          <div class="profile">
            <h4 class="profile-title">各種</h4>
            <div class="profile-box">
              <i class="far fa-calendar-alt"></i>
            </div>
            <div class="profile-box">
              <li class="profile-text"><%= link_to ">予約一覧へ", events_path %></li>
              <li class="profile-text"><%= link_to ">新規予約する", facilities_path %></li>
              <li class="profile-text"><%= link_to ">トップへ戻る", root_path %></li>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/customers/withdraw.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p class="withdraw-title">本当に退会しますか？</p>
      <p class="withdraw-message">
        退会すると、会員登録情報や<br>
        これまでの購入履歴が閲覧できなくなります。<br>
        退会する場合は、「退会する」をクリックしてください。<br>
        <%= link_to '退会しない', customer_path, class: "btn btn-primary" %>
        <%= link_to '退会する', customer_path,  method: :delete, "data-confirm" => "本当に退会しますか？", class:"btn btn-danger" %></p>
    </div>
  </div>
</div>