config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers_devise/sessions',
    passwords:     'customers_devise/passwords',
    registrations: 'customers_devise/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 ##管理者側

  namespace :admins do
    resources :customers, only: [:index,:show,:edit,:update]
    get 'facilities/:facility_id/calendar' ,to: 'facilities#calendar', as: 'facilities_calendar'
    resources :facilities, except: [:destroy] do
      resource :facility_comments, only: [:create, :destroy]
      collection do
        get 'top'
      end
    end
    resources :categories, only: [:index,:create,:edit,:update]
    resources :events, only: [:index, :show, :edit, :update, :destroy]
    get 'facilities/:facility_id/sub_facilities' ,to: 'sub_facilities#index', as: 'sub_facility_facilities'
    resources :sub_facilities, except: [:destroy]
    get 'facilities/:facility_id/informations' ,to: 'informations#index', as: 'information_facilities'
    resources :informations
  end

  ##会員側
  root to: 'homes#top'
  resource :customer, only: [:show, :edit, :update, :destroy] do
    resources :favorites, only: [:index]
    member do
      get 'withdraw'
    end
  end
  get 'events/:facility_id/new' ,to: 'events#new', as: 'new_event'
  resources :events do
    collection do
        get 'thanks'
        get 'cancel'
        get  'confirm'
        post 'confirm'
    end
  end
  get 'facilities/:facility_id/calendar' ,to: 'facilities#calendar', as: 'facilities_calendar'
  resources :facilities, only: [:index,:show] do
    get 'search', on: :collection
    resource :favorites, only: [:create, :destroy]
    resource :facility_comments, only: [:create, :destroy]
  end
  get 'facilities/:facility_id/sub_facilities' ,to: 'sub_facilities#index', as: 'sub_facility_facilities'
  resources :sub_facilities, only: [:index,:show]
  get 'facilities/:facility_id/informations' ,to: 'informations#index', as: 'information_facilities'
  resources :informations, only: [:index,:show]
  get 'homes/about' => 'homes#about'

end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :facility
  validates :title, presence: true
  validates :body, presence: true
  def new_arrival?
    created_at + 1.week > Date.today
  end
end

app/controllers/admins/informations_controller.rb
class Admins::InformationsController < ApplicationController
  def index
    @information = Information.new(facility_id: params[:facility_id])
    @informations = Information.where(facility_id: params[:facility_id]).all
  end
  def create
    @information = Information.new(information_params)
    @facility = Information.where(facility_id: params[:facility_id])
    if @information.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @information = Information.find(params[:id])
  end

  def edit
    @information = Information.find(params[:id])
  end

  def update
    @information = Information.find(params[:id])
    if @information.update(information_params)
      redirect_to admins_information_facilities_path(@information.facility.id)
    else
      render 'edit'
    end
  end
  def destroy
    @information = Information.find(params[:id])
    if @information.destroy
      redirect_back(fallback_location: root_path)
    else
    	 render action: :destroy
    end
  end
  private
  def information_params
    params.require(:information).permit(:facility_id, :title, :body)
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def index
    @informations = Information.where(facility_id: params[:facility_id]).all
  end

  def show
    @information = Information.find(params[:id])
  end
end

app/helpers/admins/informations_helper.rb
module Admins::InformationsHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/_new_label.html.erb
<div class="new-label">
  <div class="label-name">New!</div>
</div>

app/views/informations/index.html.erb
<div class ="container">
  <div class= "row">
    <div class= "col-xs-12">
      <h2>詳細画面</h2>
    </div>
  </div>
  <div class="row">
    <div class= "col-xs-3">
        <div class="sidebar">
        <%= link_to("./", class: 'list-content') do %>
        <div class="sidebar-title">基本情報</div>
      <% end %>
      <%= link_to(sub_facility_facilities_path, class: 'list-content') do %>
        <div class="sidebar-title">コート一覧</div>
        <% end %>
      <%= link_to(facilities_calendar_path, class: 'list-content') do %>
        <div class="sidebar-title">カレンダー</div>
      <% end %>
        </div>
        <%= link_to(information_facilities_path, class: 'list-content') do %>
        <div class="sidebar-title">お知らせ</div>
        <% end %>
        <%= link_to '新規予約する', new_event_path, class: 'btn btn-danger', style:"width:100%;"%>
        </div>
    <div class= "col-xs-9">
      <h3>お知らせ一覧</h3>
        <% @informations.each do |information| %>
        <%= link_to(information_path(information), class: 'list-content') do %>
        <div class="information-box">
          <ul>
            <li class="information-date"><%= information.created_at.strftime("%Y年%m月%d日")%></li>
            <li class="information-date"><%= information.title %></li>
            <% if information.new_arrival? == true %>
            <li class="information-date"><%= render 'new_label' %></li>
            <% end %>
          </ul>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/informations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>お知らせ詳細</h2>
    </div>
  </div>
  <div class="row">
    <h3>内容</h3>
      <div class="information-detail">
        <div class="information-main"><%= @information.title %></div>
        <div class="information-datetime"><%= @information.created_at.strftime("%Y年%m月%d日")%></div>
        <div class="information-content"> <%= @information.body %></div>
      </div>
      <%= link_to "戻る" , :back,class:"btn btn-primary show"%>
  </div>
</div>